# Generated by Django 3.2.6 on 2022-05-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
