# Generated by Django 3.2.6 on 2022-05-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220526_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание'),
        ),
    ]
