# Generated by Django 3.2.6 on 2022-05-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apinews', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
