# Generated by Django 3.2.6 on 2022-06-01 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apinews', '0007_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apinews',
            old_name='user',
            new_name='users',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='лайк')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apinews.apinews', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Лайки',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
