# Generated by Django 3.2.6 on 2022-06-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apinews', '0008_auto_20220602_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='img', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
