# Generated by Django 3.2.6 on 2022-05-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apinews', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='apinews.apinews', verbose_name='Пост'),
        ),
    ]
