# Generated by Django 3.2.6 on 2022-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apinews', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
